---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    attributes:
      chef-server:
        version: 12.0.7-1
  - name: ubuntu-12.04
    attributes:
      chef-server:
        version: 12.0.7-1
  - name: centos-6.6
    attributes:
      chef-server:
        version: 12.0.7-1
  - name: centos-6.4
    driver:
      box: opscode-centos-6.4
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.4_chef-provisionerless.box
    attributes:
      chef-server:
        version: 12.0.5-1

suites:
  - name: default
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef_server_populator:
        endpoint: localhost
        solo_org:
          validator_pub_key: validator_pub.pem
        org_users:
          pub_key: user_pub.pem
        clients:
          test-node: client_key_pub.pem
  - name: data-bag
    provisioner:
      name: chef_zero
    data_bags_path: test/fixtures/data_bags
    run_list:
      - recipe[test]
      - recipe[chef-server-populator]
    attributes:
      chef_server_populator:
        endpoint: localhost
        databag: chef
